num=float(input('Escreva um numero: '))
num2=float(input('Escreva um segundo numero: '))
num3=float(input('Escreva um Terceiro numero: '))
dobro_metad=((num*num2)*(num2/2))
triplo_soma=((num*3)+num3)
cubo=(num3**3)
print('O dobro do primeiro numero e a metade do segundo somando é: %.2f'%(dobro_metad))
print('a soma do triplo do primeiro com o terceiro: %.2f'%(triplo_soma))
print('o terceiro elevado ao cubo: %.2f'%(cubo))
