nome=input('Digite seu nome: ')
serie=input('Digite seu serie: ')
escola=input('Qual nome da sua escola: ')
cidade=input('Qual o nome da sua cidade: ')
n1=float(input('Digite sua n1: '))
n2=float(input('Digite sua n2: '))
n3=float(input('Digite sua n3: '))
n4=float(input('Digite sua n4: '))
media=(n1+n2+n3+n4)/4
print(nome)
print(serie)
print(escola)
print(cidade)
print(n1)
print(n2)
print(n3)
print(n4)
print('seu nome é: %s\n sua serie: %s\n O nome da escola é: %s\n sua cidade: %s\n sua media da n1, n2, n3 e n4: %.1f'%(nome,serie,escola,cidade,media))